spring.application.name=kinotower

spring.datasource.url=jdbc:postgresql://localhost:5000/db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB
file.upload-dir=files
